# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-sew-bsp"
BBFILE_PATTERN_meta-sew-bsp = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-sew-bsp = "10"

LAYERDEPENDS_meta-sew-bsp = "core raspberrypi"
LAYERSERIES_COMPAT_meta-sew-bsp = "wrynose"
